language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements-ci.txt

script:
  - make syntax
  - python setup.py develop
  - make test
